version: '3.8'

services:

  db:
    image: postgres:15.3-alpine
    container_name: postgresDB
    restart: always
    volumes:
      - "postgresData:/var/lib/postgresql/data:rw"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgresData:
