-- +goose Up
-- +goose StatementBegin
CREATE TABLE "content"."shorturl" (
    id INTEGER PRIMARY KEY,
    short_key VARCHAR(250) NOT NULL,
    full_url TEXT NOT NULL
);

ALTER TABLE "content"."shorturl" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "content"."shorturl_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "content"."shorturl"
    ADD CONSTRAINT "shorturl_short_key_key" UNIQUE (short_key);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "content"."shorturl";
-- +goose StatementEnd
